[package]
name = "entish"
version = "0.1.0"
authors = ["Damien Broka <damienbroka@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entish-derive = { path = "../entish-derive" }
